{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 3 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - backend:
            service:
              name: app-service
              port:
                number: {{ .Values.service.port }}
          path: /
          pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: ca-secret
{{- end }}