apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: default
spec:
  encryptedData:
    mongodb-replica-set-key: AgBUK7DINe+PaXgafEmPdZoWfdGWrKbUzeM0UrtO623Y6M441+6oPva1AUfp9P0WwLRupmZXdoy7Z4xq3cm47V5b3zHEiC0qfXZEXu/+z8NClOW67fA1Q4zKnaoVII2Jl99wigFYntjGXBRyCj/IV1xi+wEcxMJMJLGSEBLDld6AbODDOpTIEJvolAo6HBgMWByi0fRUt3+Qa7qYvNrAjyUHZp0JBYp5thEiDd1/2ClH8MxzTu4ELgr2/ooCiKlDd6oQiPMr75NYCZdJyvSTUtS+shZmFS4XEAhWC9Va4EXtbLFSESNmwhXkMmQfFEg56MCii4ggWLCJAqxA3lD/asu8jrPH9NnkJZSFL8+h7fRdHGUMFjUG7mUibjVr7LcPksA87A/fD/t68YQcFQvYYDVXXNc8DkuS1BCUN0PSlM75+Uu8IOiDRU9SpGFMj7ERJzBa/l06kzTpinRx1nuWJeNi7Xn7/VvzkkYkj419P7yXNBp9N8TavGRHt8vHNweLM86IKbGRAXBzlRNlk9npYWiq72XZeZSt7RvBATUMU3oY7gOi9JmY6+xr2T+XLe8Fxr4L1w7pCbIEoBjXH1iVRm1XWIVhpBYZMvEOAhDPrqP7XP5b/YWjo6ACpQcgqJEqJ7UyTB/Xs6kNLuXW9jzruPBYIDV8vruVZ0+FJ9YDdFt1t20tMdkquhTWGYbCg/RmTDgvkNg2b/PntnaOzBzJfYO0EbZVzqXjAAzRcn1pAg==
    mongodb-root-password: AgBn7vbgMJ+T+GMiMcpTs6ICYFy1+Rdqy5zBY7xvc9oI7zaxYhQcRaKhagbfVZU7/d/IxK6+S0W4xp2Ef4Dzy/b2B9uVxS04xhejoY9iWvH+EaIVFj4hW/Iz9yc4OhXWcIBzLpAzM+paZvwazUqSnwrgO2UqtZojcxoL4BIViOzBkeA+4yZer/W4DxnVBXohxqF37Gh5aczZpfE4i4+A5Qx/danaf+F8nC/BCSKQiyGiqolAlJUu3mmb51pDMAye4ElPRDYevzVOiik9IHRZZmM4jam1vOq8NN4aQir3Qnj1++vzC7oYpArdTlFqOf3GGR+7yH5aCkqCIYA6wEzw/iwwfqt7vcng9G2Z70tJydQJBZYRfeMRhyWdojycNruY1G9N1n7VFxgjbpkCeb9NJffgsYeffqhBg9D1SWqikPCoIQ89Gnu7h34eSMZGbsyny0DxgUaxaU7gLHLpnebCFs8mvy8jaxTJopGTZy135x/1Doh6ec1P2du+xoLm3ojqspDcClGmBLtvHv/PHa7/g6w73Z8asR3wZU8lqUvuyoc2b4+RqTtdvTO9Zz6LhN/YXKG4+uMPTl9iTI2FL2DA9G1kxM1pY0joU18vWmZoGGPXPTZeeUeTcVZ4LyKwYZ0xjl+BFvkKtorpjikovBJGpKz2nV9nk/Uej4gX3XQzP+LFJqDMRvDy6WOPwmgOAgkRfkLL6WmD/Q==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: default
    type: Opaque

