apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  selector:
    app: app
